In [63]:
# Load the library with the iris dataset
from sklearn.datasets import load_iris

# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Load pandas
import pandas as pd

# Load numpy
import numpy as np


In [93]:
# Create an object called iris with the iris data
df = pd.read_excel('data/Book1.xlsx')
df['v2']=df.vypusk1*1000
# View the top 5 rows
df.head()


vypusk rate_tr       vypusk1            v2
0   33777430       A  27347.555703  2.734756e+07
1   19146253       A  12939.887053  1.293989e+07
2  121972226       A  67869.464518  6.786946e+07
3   18088077       A  10677.492612  1.067749e+07
4    3011385       C   1395.065535  1.395066e+06

In [65]:
X=df.iloc[:,0:1].values
y=df.iloc[:,1].values

In [56]:
X

array([[ 33777430],
       [ 19146253],
       [121972226],
       [ 18088077],
       [  3011385],
       [ 23114100],
       [ 49949831],
       [ 27827474],
       [  3126861],
       [ 11293507],
       [ 12522958],
       [ 15789941],
       [ 11012636],
       [  4324159],
       [ 11147379],
       [ 13349431],
       [ 10076567],
       [  2287376],
       [  2358939]], dtype=int64)

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)  

In [74]:
X_test
 

array([[18088077],
       [13349431],
       [49949831],
       [12522958]], dtype=int64)

In [75]:
from sklearn.svm import SVC
#Support Vector Classifier
s_clf = SVC(gamma='auto')
s_clf.fit(X_train,y_train)
s_prediction = s_clf.predict(X_test)
print (s_prediction)

['A' 'A' 'A' 'A']


In [76]:
print(confusion_matrix(y_test, s_prediction))

[[2 0]
 [2 0]]


In [77]:
print(accuracy_score(y_test, s_prediction))

0.5


In [79]:
from sklearn.ensemble import RandomForestClassifier
#RandomForestClassifier
rfc_clf = RandomForestClassifier()
rfc_clf.fit(X,y)
rfc_prediction = rfc_clf.predict(X_test)
rfc_prediction

D:\Users\o.lukasevych\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array(['A', 'B', 'A', 'B'], dtype=object)

In [80]:
print(confusion_matrix(y_test, rfc_prediction))

[[2 0]
 [0 2]]


In [81]:
print(accuracy_score(y_test, rfc_prediction))

1.0


In [95]:
z=df.v2.values.reshape(-1,1)
z_pr=rfc_clf.predict(z)
z_pr

array(['A', 'B', 'A', 'C', 'C', 'B', 'A', 'A', 'C', 'C', 'B', 'C', 'B',
       'B', 'C', 'B', 'B', 'C', 'C'], dtype=object)

In [105]:
rfc_clf.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)